# Generated by Django 4.2.16 on 2026-04-30 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(max_length=200, verbose_name='目标地址')),
                ('result', models.TextField(verbose_name='执行结果')),
                ('executed_by', models.CharField(max_length=50, verbose_name='执行者')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'cmd_results',
            },
        ),
        migrations.CreateModel(
            name='SqliPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('author', models.CharField(max_length=50, verbose_name='作者')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sqli_posts',
            },
        ),
        migrations.CreateModel(
            name='SqliUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='用户名')),
                ('password', models.CharField(max_length=128, verbose_name='密码(MD5)')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('role', models.CharField(default='user', max_length=20, verbose_name='角色')),
            ],
            options={
                'db_table': 'sqli_users',
            },
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255, verbose_name='文件名')),
                ('filepath', models.CharField(max_length=500, verbose_name='存储路径')),
                ('uploader', models.CharField(max_length=50, verbose_name='上传者')),
                ('size', models.IntegerField(verbose_name='文件大小(字节)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'upload_files',
            },
        ),
        migrations.CreateModel(
            name='XssComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('content', models.TextField(verbose_name='评论内容')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'xss_comments',
            },
        ),
    ]
