# Generated by Django 4.2.16 on 2026-04-30 05:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0, verbose_name='积分')),
                ('level', models.CharField(choices=[('beginner', '入门'), ('intermediate', '进阶'), ('advanced', '高级')], default='beginner', max_length=20)),
                ('avatar', models.URLField(blank=True, verbose_name='头像URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '学员信息',
                'verbose_name_plural': '学员信息',
                'db_table': 'user_profile',
            },
        ),
        migrations.CreateModel(
            name='ChallengeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge_id', models.CharField(max_length=50, verbose_name='挑战ID')),
                ('challenge_name', models.CharField(max_length=100, verbose_name='挑战名称')),
                ('difficulty', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10)),
                ('status', models.CharField(choices=[('pending', '未完成'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=10)),
                ('score', models.IntegerField(default=0, verbose_name='获得积分')),
                ('writeup', models.TextField(blank=True, verbose_name='WriteUp')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '挑战记录',
                'verbose_name_plural': '挑战记录',
                'db_table': 'challenge_record',
                'unique_together': {('user', 'challenge_id', 'difficulty')},
            },
        ),
    ]
